# Generated by Django 5.1.4 on 2024-12-08 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeList', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='lastname',
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='Default', max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
