# Generated by Django 5.1.4 on 2024-12-08 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeList', '0004_role_employee'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='role_id',
            new_name='role',
        ),
        migrations.CreateModel(
            name='access_rights',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_name', models.CharField(max_length=255)),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='EmployeeList.role')),
            ],
        ),
    ]
